# SPDX-License-Identifier: MIT
---
- name: Ensure required packages are installed
  block:
    - name: Install asciidoctor requirements
      package:
        name: ruby
        state: latest
    - name: Install asciidoctor
      gem:
        name: asciidoctor
        state: latest
        user_install: no
  rescue:
    - name: Try to install asciidoctor locally from URL
      yum:
        name: http://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/asciidoctor-2.0.10-1-omv4002.noarch.rpm
        state: present

- name: Build HTML in {{ directory }} using {{ source_file }}
  asciidoctor_wrapper:
    directory: "{{ directory }}"
    source_file: "{{ source_file }}"
    output_file: "{{ output_file }}"
    force: "{{ force }}"
