# SPDX-License-Identifier: MIT
---
- name: Ensure required packages are installed
  package:
    name: asciidoctor
    state: present

- name: Build HTML in {{ directory }} using {{ source_file }}
  asciidoctor_wrapper:
    directory: "{{ directory }}"
    source_file: "{{ source_file }}"
    output_file: "{{ output_file }}"
