# SPDX-License-Identifier: MIT
---
- name: Ensure required packages are installed
  package:
    name: asciidoctor
    state: present

- name: Build HTML in {{ build_directory }} using {{ in_file }}
  asciidoctor_wrapper:
    directory: "{{ build_directory }}"
    in-file: "{{ in_file }}"
    out-file: "{{ out_file }}"
